from __future__ import annotations
from .blood_type import MaleoMetadataBloodTypeClientParametersTransfers
from .gender import MaleoMetadataGenderClientParametersTransfers
from .medical_role import MaleoMetadataMedicalRoleClientParametersTransfers
from .organization_type import MaleoMetadataOrganizationTypeClientParametersTransfers
from .service import MaleoMetadataServiceClientParametersTransfers
from .system_role import MaleoMetadataSystemRoleClientParametersTransfers
from .user_type import MaleoMetadataUserTypeClientParametersTransfers


class MaleoMetadataClientParametersTransfers:
    BloodType = MaleoMetadataBloodTypeClientParametersTransfers
    Gender = MaleoMetadataGenderClientParametersTransfers
    MedicalRole = MaleoMetadataMedicalRoleClientParametersTransfers
    OrganizationType = MaleoMetadataOrganizationTypeClientParametersTransfers
    Service = MaleoMetadataServiceClientParametersTransfers
    SystemRole = MaleoMetadataSystemRoleClientParametersTransfers
    UserType = MaleoMetadataUserTypeClientParametersTransfers
