Skyline_OutputDtype = {
    # Run
    "Replicate Name": "object",
    # Protein
    "Protein Name": "object",
    "Protein Accession": "object",
    "Protein Gene": "object",
    "Protein Abundance": "float64",
    # Peptide
    "Peptide Sequence": "object",
    "Peptide Modified Sequence Unimod Ids": "object",
    "Is Decoy": "bool",
    "Precursor Charge": "int64",
    "Precursor Mz": "float64",
    "Transition Count": "int64",
    "Predicted Retention Time": "float64",
    "Average Measured Retention Time": "float64",
    "Explicit Retention Time": "float64",
    "Peptide Peak Found Ratio": "float64",
    "Peptide Retention Time": "float64",
    "Predicted Result Retention Time": "float64",
    "Normalized Area": "float64",
    "Precursor Peak Found Ratio": "float64",
    "Best Retention Time": "float64",
    "Max Fwhm": "float64",
    "Min Start Time": "float64",
    "Max End Time": "float64",
    "Total Area": "float64",
    "Total Area MS1": "float64",
    "Total Area Fragment": "float64",
    "Total Background": "float64",
    "Total Background MS1": "float64",
    "Total Background Fragment": "float64",
    "Total Area Normalized": "object",
    "Average Mass Error PPM": "float64",
    "Identified": "object",  # Bool, and sometimes NANs
    "Library Dot Product": "float64",
    "Precursor Normalized Area": "float64",
}
