from typing import Protocol

import jax
from jaxtyping import ArrayLike


class IndexUpdateRef(Protocol):
    def get(self) -> jax.Array: ...
    def set(self, values: ArrayLike) -> jax.Array: ...
    def add(self, values: ArrayLike) -> jax.Array: ...

    # def subtract(self, values: ArrayLike) -> jax.Array: ...
    # def mul(self, values: ArrayLike) -> jax.Array: ...
    # def multiply(self, values: ArrayLike) -> jax.Array: ...
    # def divide(self, values: ArrayLike) -> jax.Array: ...
    # def power(self, values: ArrayLike) -> jax.Array: ...
    # def min(self, values: ArrayLike) -> jax.Array: ...
    # def max(self, values: ArrayLike) -> jax.Array: ...
