# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a42/data/pointcloud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'a42/data/pointcloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x34\x32/data/pointcloud.proto\x12\x08\x61\x34\x32.data\"]\n\nLidarPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x11\n\tintensity\x18\x04 \x01(\x02\x12\x1b\n\x13timestamp_offset_ns\x18\x05 \x01(\x04\"2\n\nPointCloud\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.a42.data.LidarPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a42.data.pointcloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIDARPOINT']._serialized_start=39
  _globals['_LIDARPOINT']._serialized_end=132
  _globals['_POINTCLOUD']._serialized_start=134
  _globals['_POINTCLOUD']._serialized_end=184
# @@protoc_insertion_point(module_scope)
