# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: MIT
"""VMNetworkInterfaceAttributes class."""
from enum import Enum


class VMNetworkInterfaceAttributes(str, Enum):
    """Attributes of VM network interface."""

    def __str__(self) -> str:
        return str.__str__(self)

    DynamicMacAddressEnabled = "dynamicmacaddressenabled"
    AllowPacketDirect = "allowpacketdirect"
    NumaAwarePlacement = "numaawareplacement"
    MacAddressSpoofing = "macaddressspoofing"
    AllowTeaming = "allowteaming"
    RouterGuard = "routerguard"
    DhcpGuard = "dhcpguard"
    StormLimit = "stormlimit"
    PortMirroringMode = "portmirroringmode"
    IeeePriorityTag = "ieeeprioritytag"
    VirtualSubnetId = "virtualsubnetid"
    DynamicIPAddressLimit = "dynamicipaddresslimit"
    DeviceNaming = "devicename"
    VmqWeight = "vmqweight"
    VmqUsage = "vmqusage"
    IovWeight = "iovweight"
    IovUsage = "iovusage"
    IovQueuePairsRequested = "iovqueuepairsrequested"
    IovQueuePairsAssigned = "iovqueuepairsassigned"
    IovInterruptModeration = "iovinterruptmoderation"
    PacketDirectNumProcs = "packetdirectnumprocs"
    PacketDirectModerationCount = "packetdirectmoderationcount"
    PacketDirectModerationInterval = "packetdirectmoderationinterval"
    VrssEnabledRequested = "vrssenabledrequested"
    VrssEnabled = "vrssenabled"
    VmmqEnabledRequested = "vmmqenabledrequested"
    VmmqEnabled = "vmmqenabled"
    VrssMaxQueuePairsRequested = "vrssmaxqueuepairsrequested"
    VrssMaxQueuePairs = "vrssmaxqueuepairs"
    VrssMinQueuePairsRequested = "vrssminqueuepairsrequested"
    VrssMinQueuePairs = "vrssminqueuepairs"
    VrssQueueSchedulingModeRequested = "vrssqueueschedulingmoderequested"
    VrssQueueSchedulingMode = "vrssqueueschedulingmode"
    VrssExcludePrimaryProcessorRequested = "vrssexcludeprimaryprocessorrequested"
    VrssExcludePrimaryProcessor = "vrssexcludeprimaryprocessor"
    VrssIndependentHostSpreadingRequested = "vrssindependenthostspreadingrequested"
    VrssIndependentHostSpreading = "vrssindependenthostspreading"
    VrssVmbusChannelAffinityPolicyRequested = "vrssvmbuschannelaffinitypolicyrequested"
    VrssVmbusChannelAffinityPolicy = "vrssvmbuschannelaffinitypolicy"
    RscEnabledRequested = "rscenabledrequested"
    RscEnabled = "rscenabled"
    IPsecOffloadMaxSA = "ipsecoffloadmaxsa"
    IPsecOffloadSAUsage = "ipsecoffloadsausage"
    VFDataPathActive = "vfdatapathactive"
    MaximumBandwidth = "maximumbandwidth"
    MinimumBandwidthAbsolute = "minimumbandwidthabsolute"
    MinimumBandwidthWeight = "minimumbandwidthweight"
    BandwidthPercentage = "bandwidthpercentage"
    VmmqQueuePairs = "vmmqqueuepairs"
    StaticMacAddress = "staticmacaddress"
