from setuptools import setup, find_packages

setup(
    name='RadEval',
    version='0.0.1rc0',
    author='Jean-Benoit Delbrouck, Justin Xu, Xi Zhang',
    maintainer='Xi Zhang',
    url='https://github.com/jbdel/RadEval',
    project_urls={
        'Bug Reports': 'https://github.com/jbdel/RadEval/issues',
        'Source': 'https://github.com/jbdel/RadEval',
        'Documentation': 'https://github.com/jbdel/RadEval/blob/main/README.md',
    },
    license='MIT',
    description='All-in-one metrics for evaluating AI-generated radiology text',
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3 :: Only',
    ],
    keywords=[
        'radiology',
        'evaluation',
        'natural language processing',
        'radiology report',
        'medical NLP',
        'clinical text generation',
        'LLM',
        'bioNLP',
        'chexbert',
        'radgraph',
        'medical AI'
    ],
    python_requires='>=3.9,<=3.12.1',
    install_requires=[
        'torch>=2.2.2,<3.0',
        'transformers>=4.53.1',
        'radgraph',
        'rouge_score',
        'bert-score==0.3.13',
        'scikit-learn',
        'numpy<2',
        'medspacy',
        'stanza',
        'accelerate==0.30.1',
        'pillow==10.3.0',
        'sentencepiece==0.2.0',
        'sentence-transformers==3.0.1',
        'datasets==2.19.0',
        'torchvision==0.17.2',
        'opencv-python==4.10.0.84',
        'scipy',
        'matplotlib',
        'pandas'
    ],
    packages=find_packages(),
    zip_safe=False,
    )