# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enumeration

class BrokerTransportQualityOfService(object):
    NotSpecified = 0
    BestEffort = 1
    AtLeastOnce = 2
    AtMostOnce = 3
    ExactlyOnce = 4
