# automatically generated by the FlatBuffers compiler, do not modify

# namespace: enumeration

class UserTokenType(object):
    Anonymous = 0
    UserName = 1
    Certificate = 2
    IssuedToken = 3
