# automatically generated by the FlatBuffers compiler, do not modify

# namespace: client

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TokenCert(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TokenCert()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTokenCert(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TokenCert
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TokenCert
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TokenCert
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TokenCertStart(builder): builder.StartObject(2)
def Start(builder):
    return TokenCertStart(builder)
def TokenCertAddLocation(builder, location): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AddLocation(builder, location):
    return TokenCertAddLocation(builder, location)
def TokenCertAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return TokenCertAddName(builder, name)
def TokenCertEnd(builder): return builder.EndObject()
def End(builder):
    return TokenCertEnd(builder)

class TokenCertT(object):

    # TokenCertT
    def __init__(self):
        self.location = None  # type: str
        self.name = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tokenCert = TokenCert()
        tokenCert.Init(buf, pos)
        return cls.InitFromObj(tokenCert)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tokenCert):
        x = TokenCertT()
        x._UnPack(tokenCert)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.location == other.location and \
            self.name == other.name

    # TokenCertT
    def _UnPack(self, tokenCert):
        if tokenCert is None:
            return
        self.location = tokenCert.Location()
        self.name = tokenCert.Name()

    # TokenCertT
    def Pack(self, builder):
        if self.location is not None:
            location = builder.CreateString(self.location)
        if self.name is not None:
            name = builder.CreateString(self.name)
        TokenCertStart(builder)
        if self.location is not None:
            TokenCertAddLocation(builder, location)
        if self.name is not None:
            TokenCertAddName(builder, name)
        tokenCert = TokenCertEnd(builder)
        return tokenCert
