key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIG4BOpPiAtfiRgc2DydA/wkdxOGaxwH+exd4MXa4Cja8oAoGCCqGSM49
AwEHoUQDQgAEDS/OWw/BDHH2l2pZO6LPmWqNUKmuPNSJ7xbtVxsIpuJwNxntrch6
qbU2VrVjYuzRAjQvjff9rgC9kJLGi+Z2OQ==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6DCCAY8CFAnIVb8H7lNPfebaSJJTQ0vn9OfhMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTA3MTAwNjM3MDNaFw0zNTA3MDgwNjM3
MDNaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABA0vzlsPwQxx9pdqWTuiz5lqjVCprjzUie8W7VcbCKbicDcZ7a3Ieqm1
Nla1Y2Ls0QI0L433/a4AvZCSxovmdjkwCgYIKoZIzj0EAwIDRwAwRAIgWFa5O1DU
knIrEdqRN1AoSccEbIVQM9q3W+IC0xFHeU8CIDOfBI4Tn40oE+85IslFMVLZaXGK
eD4SF5N8kWIN6UxT
-----END CERTIFICATE-----
"""