# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20250708
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from lexmachina.models.originating_district_court_case_judges_inner import OriginatingDistrictCourtCaseJudgesInner
from typing import Optional, Set
from typing_extensions import Self

class OriginatingDistrictCourtCase(BaseModel):
    """
    OriginatingDistrictCourtCase
    """ # noqa: E501
    district_case_id: StrictInt = Field(alias="districtCaseId")
    district_case_url: StrictStr = Field(alias="districtCaseUrl")
    judges: List[OriginatingDistrictCourtCaseJudgesInner]
    case_types: List[StrictStr] = Field(alias="caseTypes")
    __properties: ClassVar[List[str]] = ["districtCaseId", "districtCaseUrl", "judges", "caseTypes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OriginatingDistrictCourtCase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in judges (list)
        _items = []
        if self.judges:
            for _item_judges in self.judges:
                if _item_judges:
                    _items.append(_item_judges.to_dict())
            _dict['judges'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OriginatingDistrictCourtCase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "districtCaseId": obj.get("districtCaseId"),
            "districtCaseUrl": obj.get("districtCaseUrl"),
            "judges": [OriginatingDistrictCourtCaseJudgesInner.from_dict(_item) for _item in obj["judges"]] if obj.get("judges") is not None else None,
            "caseTypes": obj.get("caseTypes")
        })
        return _obj


