MaxQuant_EviDtype = {
    "Sequence": "str",
    "Length": "int64",
    "Modifications": "object",
    "Modified sequence": "str",
    "Oxidation (M) Probabilities": "object",
    "Oxidation (M) Score Diffs": "object",
    "Oxidation (M)": "int64",
    "Missed cleavages": "int64",
    "Proteins": "object",
    "Leading proteins": "object",
    "Leading razor protein": "object",
    "Gene names": "object",
    "Protein names": "object",
    "Type": "str",
    "Raw file": "str",
    "Experiment": "object",
    "MS/MS m/z": "float64",
    "Charge": "int64",
    "m/z": "float64",
    "Mass": "float64",
    "Uncalibrated - Calibrated m/z [ppm]": "float64",
    "Uncalibrated - Calibrated m/z [Da]": "float64",
    "Mass error [ppm]": "float64",
    "Mass error [Da]": "float64",
    "Uncalibrated mass error [ppm]": "float64",
    "Uncalibrated mass error [Da]": "float64",
    "Max intensity m/z 0": "float64",
    "Retention time": "float64",
    "Retention length": "float64",
    "Calibrated retention time": "float64",
    "Calibrated retention time start": "float64",
    "Calibrated retention time finish": "float64",
    "Retention time calibration": "float64",
    "Match time difference": "float64",
    "Match m/z difference": "float64",
    "Match q-value": "float64",
    "Match score": "float64",
    "Number of data points": "float64",
    "Number of scans": "float64",
    "Number of isotopic peaks": "float64",
    "PIF": "float64",
    "Fraction of total spectrum": "float64",
    "Base peak fraction": "float64",
    "PEP": "float64",
    "MS/MS count": "int64",
    "MS/MS scan number": "float64",
    "Score": "float64",
    "Delta score": "float64",
    "Combinatorics": "int64",
    "Library index": "int64",
    "Sample rt - library rt": "float64",
    "Library rt": "float64",
    "Precursor found": "object",
    "Fragment overlap": "int64",
    "Intensity correlation": "float64",
    "Precursor num scans": "int64",
    "Fragment median num scans": "float64",
    "Precursor has isotope pattern": "object",
    "Number of fragments": "int64",
    "Mass difference to range min": "float64",
    "Mass difference to range max": "float64",
    "Intensity": "float64",
    "Reverse": "object",
    "Potential contaminant": "object",
    "id": "int64",
    "Protein group IDs": "object",
    "Peptide ID": "object",
    "Mod. peptide ID": "object",
    "MS/MS IDs": "object",
    "Best MS/MS": "object",
    "Carbamidomethyl (C) site IDs": "object",
    "Oxidation (M) site IDs": "object",
    "Taxonomy IDs": "object",
}
