#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2504-13-g41893720"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2504
#define NETGEN_VERSION_TWEAK 13
#define NETGEN_VERSION_HASH "g41893720"
#endif // NETGEN_VERSION_HPP_INCLUDED
