# Generated by Django 5.2.4 on 2025-07-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictext',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dynamictext',
            name='content_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dynamictext',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamictext',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
