# automatically generated by the FlatBuffers compiler, do not modify

# namespace: builtin

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArrayOfGuid(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArrayOfGuid()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArrayOfGuid(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArrayOfGuid
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArrayOfGuid
    def Array(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from comm.opcua.builtin.Guid import Guid
            obj = Guid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ArrayOfGuid
    def ArrayLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArrayOfGuid
    def ArrayIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ArrayOfGuidStart(builder): builder.StartObject(1)
def Start(builder):
    return ArrayOfGuidStart(builder)
def ArrayOfGuidAddArray(builder, array): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(array), 0)
def AddArray(builder, array):
    return ArrayOfGuidAddArray(builder, array)
def ArrayOfGuidStartArrayVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartArrayVector(builder, numElems):
    return ArrayOfGuidStartArrayVector(builder, numElems)
def ArrayOfGuidEnd(builder): return builder.EndObject()
def End(builder):
    return ArrayOfGuidEnd(builder)
import comm.opcua.builtin.Guid
try:
    from typing import List
except:
    pass

class ArrayOfGuidT(object):

    # ArrayOfGuidT
    def __init__(self):
        self.array = None  # type: List[comm.opcua.builtin.Guid.GuidT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        arrayOfGuid = ArrayOfGuid()
        arrayOfGuid.Init(buf, pos)
        return cls.InitFromObj(arrayOfGuid)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, arrayOfGuid):
        x = ArrayOfGuidT()
        x._UnPack(arrayOfGuid)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.array == other.array

    # ArrayOfGuidT
    def _UnPack(self, arrayOfGuid):
        if arrayOfGuid is None:
            return
        if not arrayOfGuid.ArrayIsNone():
            self.array = []
            for i in range(arrayOfGuid.ArrayLength()):
                if arrayOfGuid.Array(i) is None:
                    self.array.append(None)
                else:
                    guid_ = comm.opcua.builtin.Guid.GuidT.InitFromObj(arrayOfGuid.Array(i))
                    self.array.append(guid_)

    # ArrayOfGuidT
    def Pack(self, builder):
        if self.array is not None:
            arraylist = []
            for i in range(len(self.array)):
                arraylist.append(self.array[i].Pack(builder))
            ArrayOfGuidStartArrayVector(builder, len(self.array))
            for i in reversed(range(len(self.array))):
                builder.PrependUOffsetTRelative(arraylist[i])
            array = builder.EndVector()
        ArrayOfGuidStart(builder)
        if self.array is not None:
            ArrayOfGuidAddArray(builder, array)
        arrayOfGuid = ArrayOfGuidEnd(builder)
        return arrayOfGuid
