# automatically generated by the FlatBuffers compiler, do not modify

# namespace: builtin

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UInt64Variant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UInt64Variant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUInt64Variant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UInt64Variant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UInt64Variant
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def UInt64VariantStart(builder): builder.StartObject(1)
def Start(builder):
    return UInt64VariantStart(builder)
def UInt64VariantAddValue(builder, value): builder.PrependUint64Slot(0, value, 0)
def AddValue(builder, value):
    return UInt64VariantAddValue(builder, value)
def UInt64VariantEnd(builder): return builder.EndObject()
def End(builder):
    return UInt64VariantEnd(builder)

class UInt64VariantT(object):

    # UInt64VariantT
    def __init__(self):
        self.value = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uint64Variant = UInt64Variant()
        uint64Variant.Init(buf, pos)
        return cls.InitFromObj(uint64Variant)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uint64Variant):
        x = UInt64VariantT()
        x._UnPack(uint64Variant)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.value == other.value

    # UInt64VariantT
    def _UnPack(self, uint64Variant):
        if uint64Variant is None:
            return
        self.value = uint64Variant.Value()

    # UInt64VariantT
    def Pack(self, builder):
        UInt64VariantStart(builder)
        UInt64VariantAddValue(builder, self.value)
        uint64Variant = UInt64VariantEnd(builder)
        return uint64Variant
