# coding=utf-8


from ._operations import (
    YieldBookRestOperations,
    bondFutureOperations,
    bondOperations,
    calendarResourceOperations,
    calendarsResourceOperations,
    capFloorOperations,
    cdsOperations,
    commoditiesCurvesOperations,
    creditCurvesOperations,
    eqVolatilityOperations,
    floatingRateIndexResourceOperations,
    floatingRateIndicesResourceOperations,
    forwardRateAgreementOperations,
    fxForwardCurveResourceOperations,
    fxForwardCurvesResourceOperations,
    fxForwardResourceOperations,
    fxForwardsResourceOperations,
    fxSpotResourceOperations,
    fxSpotsResourceOperations,
    fxVolatilityOperations,
    inflationCurvesOperations,
    instrumentTemplateResourceOperations,
    instrumentTemplatesResourceOperations,
    interestRateCurveServiceOperations,
    interestRateCurvesServiceOperations,
    ipaInterestRateCurvesOperations,
    ircapletVolatilityOperations,
    irSwapResourceOperations,
    irSwapsResourceOperations,
    irswaptionVolatilityOperations,
    loanResourceOperations,
    loansResourceOperations,
    optionResourceOperations,
    optionsResourceOperations,
    repoOperations,
    structuredProductsOperations,
    swaptionOperations,
    termDepositOperations,
)
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import __all__ as _patch_all
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "calendarsResourceOperations",
    "calendarResourceOperations",
    "fxForwardCurvesResourceOperations",
    "fxForwardCurveResourceOperations",
    "fxForwardsResourceOperations",
    "fxForwardResourceOperations",
    "fxSpotsResourceOperations",
    "fxSpotResourceOperations",
    "YieldBookRestOperations",
    "instrumentTemplatesResourceOperations",
    "instrumentTemplateResourceOperations",
    "irSwapsResourceOperations",
    "irSwapResourceOperations",
    "floatingRateIndicesResourceOperations",
    "floatingRateIndexResourceOperations",
    "commoditiesCurvesOperations",
    "creditCurvesOperations",
    "inflationCurvesOperations",
    "ipaInterestRateCurvesOperations",
    "bondOperations",
    "bondFutureOperations",
    "capFloorOperations",
    "cdsOperations",
    "forwardRateAgreementOperations",
    "repoOperations",
    "structuredProductsOperations",
    "swaptionOperations",
    "termDepositOperations",
    "eqVolatilityOperations",
    "fxVolatilityOperations",
    "ircapletVolatilityOperations",
    "irswaptionVolatilityOperations",
    "optionsResourceOperations",
    "optionResourceOperations",
    "interestRateCurvesServiceOperations",
    "interestRateCurveServiceOperations",
    "loansResourceOperations",
    "loanResourceOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
