def add(a: int, b: int) -> int: ...

class ArrayD1:
    def __init__(self, *, size: int) -> None: ...
    def get(self, n: int) -> float: ...
    def set(self, n: int, d: float) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...

class ArrayD2:
    def __init__(self, *, rows: int, cols: int) -> None: ...
