# Generated by Django 5.2.3 on 2025-07-08 20:37
from django.db import migrations
from sequences.models import Sequence


def update_sequences(apps, schema_editor):
    obj = Sequence.objects.get(name="edc_pharmacy.stocktransferconfirmation")
    obj.name = "edc_pharmacy.confirmationatsite"
    obj.save()
    obj = Sequence.objects.get(name="edc_pharmacy.stocktransferconfirmationitem")
    obj.name = "edc_pharmacy.confirmationatsiteitem"
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0085_alter_confirmationatsite_options_and_more"),
    ]

    operations = [migrations.RunPython(update_sequences)]
