# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DeviceConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeviceConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DeviceConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceConfig
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceConfig
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DeviceConfigStart(builder): builder.StartObject(2)
def Start(builder):
    return DeviceConfigStart(builder)
def DeviceConfigAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return DeviceConfigAddName(builder, name)
def DeviceConfigAddDescription(builder, description): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)
def AddDescription(builder, description):
    return DeviceConfigAddDescription(builder, description)
def DeviceConfigEnd(builder): return builder.EndObject()
def End(builder):
    return DeviceConfigEnd(builder)

class DeviceConfigT(object):

    # DeviceConfigT
    def __init__(self):
        self.name = None  # type: str
        self.description = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        deviceConfig = DeviceConfig()
        deviceConfig.Init(buf, pos)
        return cls.InitFromObj(deviceConfig)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, deviceConfig):
        x = DeviceConfigT()
        x._UnPack(deviceConfig)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.name == other.name and \
            self.description == other.description

    # DeviceConfigT
    def _UnPack(self, deviceConfig):
        if deviceConfig is None:
            return
        self.name = deviceConfig.Name()
        self.description = deviceConfig.Description()

    # DeviceConfigT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.description is not None:
            description = builder.CreateString(self.description)
        DeviceConfigStart(builder)
        if self.name is not None:
            DeviceConfigAddName(builder, name)
        if self.description is not None:
            DeviceConfigAddDescription(builder, description)
        deviceConfig = DeviceConfigEnd(builder)
        return deviceConfig
