# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ParameterResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParameterResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParameterResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ParameterResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParameterResponse
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ParameterResponse
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ParameterResponse
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParameterResponse
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ParameterResponseStart(builder): builder.StartObject(1)
def Start(builder):
    return ParameterResponseStart(builder)
def ParameterResponseAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AddData(builder, data):
    return ParameterResponseAddData(builder, data)
def ParameterResponseStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartDataVector(builder, numElems):
    return ParameterResponseStartDataVector(builder, numElems)
def ParameterResponseEnd(builder): return builder.EndObject()
def End(builder):
    return ParameterResponseEnd(builder)
try:
    from typing import List
except:
    pass

class ParameterResponseT(object):

    # ParameterResponseT
    def __init__(self):
        self.data = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        parameterResponse = ParameterResponse()
        parameterResponse.Init(buf, pos)
        return cls.InitFromObj(parameterResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, parameterResponse):
        x = ParameterResponseT()
        x._UnPack(parameterResponse)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.data == other.data

    # ParameterResponseT
    def _UnPack(self, parameterResponse):
        if parameterResponse is None:
            return
        if not parameterResponse.DataIsNone():
            if np is None:
                self.data = []
                for i in range(parameterResponse.DataLength()):
                    self.data.append(parameterResponse.Data(i))
            else:
                self.data = parameterResponse.DataAsNumpy()

    # ParameterResponseT
    def Pack(self, builder):
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                ParameterResponseStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependUint8(self.data[i])
                data = builder.EndVector()
        ParameterResponseStart(builder)
        if self.data is not None:
            ParameterResponseAddData(builder, data)
        parameterResponse = ParameterResponseEnd(builder)
        return parameterResponse
