# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# configuration of the retract motion direction (single access) in the motion kernel kinematics function 'belt synchronization'
class KinCfgBeltRetractDirectionType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinCfgBeltRetractDirectionType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKinCfgBeltRetractDirectionType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KinCfgBeltRetractDirectionType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # direction of the retract motion in case of an error in the kinematics function 'belt synchronization'
    # KinCfgBeltRetractDirectionType
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 4

def KinCfgBeltRetractDirectionTypeStart(builder): builder.StartObject(1)
def Start(builder):
    return KinCfgBeltRetractDirectionTypeStart(builder)
def KinCfgBeltRetractDirectionTypeAddValue(builder, value): builder.PrependInt8Slot(0, value, 4)
def AddValue(builder, value):
    return KinCfgBeltRetractDirectionTypeAddValue(builder, value)
def KinCfgBeltRetractDirectionTypeEnd(builder): return builder.EndObject()
def End(builder):
    return KinCfgBeltRetractDirectionTypeEnd(builder)

class KinCfgBeltRetractDirectionTypeT(object):

    # KinCfgBeltRetractDirectionTypeT
    def __init__(self):
        self.value = 4  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        kinCfgBeltRetractDirectionType = KinCfgBeltRetractDirectionType()
        kinCfgBeltRetractDirectionType.Init(buf, pos)
        return cls.InitFromObj(kinCfgBeltRetractDirectionType)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, kinCfgBeltRetractDirectionType):
        x = KinCfgBeltRetractDirectionTypeT()
        x._UnPack(kinCfgBeltRetractDirectionType)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.value == other.value

    # KinCfgBeltRetractDirectionTypeT
    def _UnPack(self, kinCfgBeltRetractDirectionType):
        if kinCfgBeltRetractDirectionType is None:
            return
        self.value = kinCfgBeltRetractDirectionType.Value()

    # KinCfgBeltRetractDirectionTypeT
    def Pack(self, builder):
        KinCfgBeltRetractDirectionTypeStart(builder)
        KinCfgBeltRetractDirectionTypeAddValue(builder, self.value)
        kinCfgBeltRetractDirectionType = KinCfgBeltRetractDirectionTypeEnd(builder)
        return kinCfgBeltRetractDirectionType
