# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Table for just one single string (can be used for strings and enums)
class KVPCfgString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KVPCfgString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKVPCfgString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KVPCfgString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # the value
    # KVPCfgString
    def StringVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KVPCfgStringStart(builder): builder.StartObject(1)
def Start(builder):
    return KVPCfgStringStart(builder)
def KVPCfgStringAddStringVal(builder, stringVal): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stringVal), 0)
def AddStringVal(builder, stringVal):
    return KVPCfgStringAddStringVal(builder, stringVal)
def KVPCfgStringEnd(builder): return builder.EndObject()
def End(builder):
    return KVPCfgStringEnd(builder)

class KVPCfgStringT(object):

    # KVPCfgStringT
    def __init__(self):
        self.stringVal = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        kvpcfgString = KVPCfgString()
        kvpcfgString.Init(buf, pos)
        return cls.InitFromObj(kvpcfgString)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, kvpcfgString):
        x = KVPCfgStringT()
        x._UnPack(kvpcfgString)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.stringVal == other.stringVal

    # KVPCfgStringT
    def _UnPack(self, kvpcfgString):
        if kvpcfgString is None:
            return
        self.stringVal = kvpcfgString.StringVal()

    # KVPCfgStringT
    def Pack(self, builder):
        if self.stringVal is not None:
            stringVal = builder.CreateString(self.stringVal)
        KVPCfgStringStart(builder)
        if self.stringVal is not None:
            KVPCfgStringAddStringVal(builder, stringVal)
        kvpcfgString = KVPCfgStringEnd(builder)
        return kvpcfgString
