# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

# Use a union for a single value (which might have one of the supported types)
class KVPCfgSingleItemValue(object):
    NONE = 0
    KVPCfgInt64 = 1
    KVPCfgDouble = 2
    KVPCfgBool = 3
    KVPCfgString = 4
    KVPCfgDoubleUnit = 5
    KVPCfgInt64Vector = 6
    KVPCfgDoubleVector = 7
    KVPCfgBoolVector = 8
    KVPCfgStringVector = 9
    KVPCfgDoubleUnitVector = 10

def KvpcfgSingleItemValueCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == KVPCfgSingleItemValue().KVPCfgInt64:
        import motion.core.fbtypes.KVPCfgInt64
        return motion.core.fbtypes.KVPCfgInt64.KVPCfgInt64T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgDouble:
        import motion.core.fbtypes.KVPCfgDouble
        return motion.core.fbtypes.KVPCfgDouble.KVPCfgDoubleT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgBool:
        import motion.core.fbtypes.KVPCfgBool
        return motion.core.fbtypes.KVPCfgBool.KVPCfgBoolT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgString:
        import motion.core.fbtypes.KVPCfgString
        return motion.core.fbtypes.KVPCfgString.KVPCfgStringT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgDoubleUnit:
        import motion.core.fbtypes.KVPCfgDoubleUnit
        return motion.core.fbtypes.KVPCfgDoubleUnit.KVPCfgDoubleUnitT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgInt64Vector:
        import motion.core.fbtypes.KVPCfgInt64Vector
        return motion.core.fbtypes.KVPCfgInt64Vector.KVPCfgInt64VectorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgDoubleVector:
        import motion.core.fbtypes.KVPCfgDoubleVector
        return motion.core.fbtypes.KVPCfgDoubleVector.KVPCfgDoubleVectorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgBoolVector:
        import motion.core.fbtypes.KVPCfgBoolVector
        return motion.core.fbtypes.KVPCfgBoolVector.KVPCfgBoolVectorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgStringVector:
        import motion.core.fbtypes.KVPCfgStringVector
        return motion.core.fbtypes.KVPCfgStringVector.KVPCfgStringVectorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KVPCfgSingleItemValue().KVPCfgDoubleUnitVector:
        import motion.core.fbtypes.KVPCfgDoubleUnitVector
        return motion.core.fbtypes.KVPCfgDoubleUnitVector.KVPCfgDoubleUnitVectorT.InitFromBuf(table.Bytes, table.Pos)
    return None
