# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Table for a vector of int64 values
class KVPCfgInt64Vector(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KVPCfgInt64Vector()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKVPCfgInt64Vector(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KVPCfgInt64Vector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # vector of int64 numbers
    # KVPCfgInt64Vector
    def IntVector(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # KVPCfgInt64Vector
    def IntVectorAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # KVPCfgInt64Vector
    def IntVectorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KVPCfgInt64Vector
    def IntVectorIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def KVPCfgInt64VectorStart(builder): builder.StartObject(1)
def Start(builder):
    return KVPCfgInt64VectorStart(builder)
def KVPCfgInt64VectorAddIntVector(builder, intVector): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(intVector), 0)
def AddIntVector(builder, intVector):
    return KVPCfgInt64VectorAddIntVector(builder, intVector)
def KVPCfgInt64VectorStartIntVectorVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartIntVectorVector(builder, numElems):
    return KVPCfgInt64VectorStartIntVectorVector(builder, numElems)
def KVPCfgInt64VectorEnd(builder): return builder.EndObject()
def End(builder):
    return KVPCfgInt64VectorEnd(builder)
try:
    from typing import List
except:
    pass

class KVPCfgInt64VectorT(object):

    # KVPCfgInt64VectorT
    def __init__(self):
        self.intVector = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        kvpcfgInt64Vector = KVPCfgInt64Vector()
        kvpcfgInt64Vector.Init(buf, pos)
        return cls.InitFromObj(kvpcfgInt64Vector)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, kvpcfgInt64Vector):
        x = KVPCfgInt64VectorT()
        x._UnPack(kvpcfgInt64Vector)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.intVector == other.intVector

    # KVPCfgInt64VectorT
    def _UnPack(self, kvpcfgInt64Vector):
        if kvpcfgInt64Vector is None:
            return
        if not kvpcfgInt64Vector.IntVectorIsNone():
            if np is None:
                self.intVector = []
                for i in range(kvpcfgInt64Vector.IntVectorLength()):
                    self.intVector.append(kvpcfgInt64Vector.IntVector(i))
            else:
                self.intVector = kvpcfgInt64Vector.IntVectorAsNumpy()

    # KVPCfgInt64VectorT
    def Pack(self, builder):
        if self.intVector is not None:
            if np is not None and type(self.intVector) is np.ndarray:
                intVector = builder.CreateNumpyVector(self.intVector)
            else:
                KVPCfgInt64VectorStartIntVectorVector(builder, len(self.intVector))
                for i in reversed(range(len(self.intVector))):
                    builder.PrependInt64(self.intVector[i])
                intVector = builder.EndVector()
        KVPCfgInt64VectorStart(builder)
        if self.intVector is not None:
            KVPCfgInt64VectorAddIntVector(builder, intVector)
        kvpcfgInt64Vector = KVPCfgInt64VectorEnd(builder)
        return kvpcfgInt64Vector
