# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

# type of the safe areas execution error reaction
class SafeAreasExecErrReaction(object):
    # brake on path with commanded dynamics, if an violation of the safe areas occurred
    LIGHT_ERROR = 0
    # stop each axis individually with maximum dynamics if an violation of the safe areas occurred
    SEVERE_ERROR = 1
