# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: syntax.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'syntax.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csyntax.proto\x12\x19pomagma.compiler.protobuf\"\xad\x01\n\tSignature\x12\x19\n\x11nullary_functions\x18\x04 \x03(\t\x12\x1b\n\x13injective_functions\x18\x06 \x03(\t\x12\x18\n\x10\x62inary_functions\x18\x07 \x03(\t\x12\x1b\n\x13symmetric_functions\x18\x08 \x03(\t\x12\x17\n\x0funary_relations\x18\t \x03(\t\x12\x18\n\x10\x62inary_relations\x18\n \x03(\t\"\x1c\n\nExpression\x12\x0e\n\x06polish\x18\x01 \x01(\t\"\x80\x01\n\x07Sequent\x12:\n\x0b\x61ntecedents\x18\x01 \x03(\x0b\x32%.pomagma.compiler.protobuf.Expression\x12\x39\n\nsuccedents\x18\x02 \x03(\x0b\x32%.pomagma.compiler.protobuf.Expression\"q\n\x06Theory\x12\x34\n\x05\x66\x61\x63ts\x18\x01 \x03(\x0b\x32%.pomagma.compiler.protobuf.Expression\x12\x31\n\x05rules\x18\x02 \x03(\x0b\x32\".pomagma.compiler.protobuf.Sequent\"z\n\x0cPresentation\x12\x37\n\tsignature\x18\x01 \x01(\x0b\x32$.pomagma.compiler.protobuf.Signature\x12\x31\n\x06theory\x18\x02 \x01(\x0b\x32!.pomagma.compiler.protobuf.Theory\"\x9d\x01\n\x06\x43orpus\x12\x41\n\x0b\x64\x65\x66initions\x18\x01 \x03(\x0b\x32,.pomagma.compiler.protobuf.Corpus.Definition\x1aP\n\nDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.pomagma.compiler.protobuf.Expressionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syntax_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNATURE']._serialized_start=44
  _globals['_SIGNATURE']._serialized_end=217
  _globals['_EXPRESSION']._serialized_start=219
  _globals['_EXPRESSION']._serialized_end=247
  _globals['_SEQUENT']._serialized_start=250
  _globals['_SEQUENT']._serialized_end=378
  _globals['_THEORY']._serialized_start=380
  _globals['_THEORY']._serialized_end=493
  _globals['_PRESENTATION']._serialized_start=495
  _globals['_PRESENTATION']._serialized_end=617
  _globals['_CORPUS']._serialized_start=620
  _globals['_CORPUS']._serialized_end=777
  _globals['_CORPUS_DEFINITION']._serialized_start=697
  _globals['_CORPUS_DEFINITION']._serialized_end=777
# @@protoc_insertion_point(module_scope)
