# automatically generated by the FlatBuffers compiler, do not modify

# namespace: subtypesunion

class ConnectionTransportDataType(object):
    NONE = 0
    comm_opcua_structure_DatagramConnectionTransportDataType = 1
    comm_opcua_structure_BrokerConnectionTransportDataType = 2
    comm_opcua_structure_DatagramConnectionTransport2DataType = 3

def ConnectionTransportDataTypeCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == ConnectionTransportDataType().comm_opcua_structure_DatagramConnectionTransportDataType:
        import comm.opcua.structure.DatagramConnectionTransportDataType
        return comm.opcua.structure.DatagramConnectionTransportDataType.DatagramConnectionTransportDataTypeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ConnectionTransportDataType().comm_opcua_structure_BrokerConnectionTransportDataType:
        import comm.opcua.structure.BrokerConnectionTransportDataType
        return comm.opcua.structure.BrokerConnectionTransportDataType.BrokerConnectionTransportDataTypeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == ConnectionTransportDataType().comm_opcua_structure_DatagramConnectionTransport2DataType:
        import comm.opcua.structure.DatagramConnectionTransport2DataType
        return comm.opcua.structure.DatagramConnectionTransport2DataType.DatagramConnectionTransport2DataTypeT.InitFromBuf(table.Bytes, table.Pos)
    return None
