cmake_minimum_required(VERSION 3.27)

include_guard(GLOBAL)

if(NOT DEFINED CMAKE_CROSSCOMPILING)
    if(CMAKE_SYSTEM_NAME AND CMAKE_HOST_SYSTEM_NAME AND NOT CMAKE_SYSTEM_NAME STREQUAL CMAKE_HOST_SYSTEM_NAME)
        set(CMAKE_CROSSCOMPILING ON)
    elseif(CMAKE_SYSTEM_PROCESSOR AND CMAKE_HOST_SYSTEM_PROCESSOR AND NOT CMAKE_SYSTEM_PROCESSOR STREQUAL CMAKE_HOST_SYSTEM_PROCESSOR)
        set(CMAKE_CROSSCOMPILING ON)
    else()
        set(CMAKE_CROSSCOMPILING OFF)
    endif()
endif()

string(APPEND CMAKE_C_FLAGS_INIT   " -utf-8")
string(APPEND CMAKE_CXX_FLAGS_INIT " -utf-8")

include("${CMAKE_CURRENT_LIST_DIR}/setup-msvc-vars.cmake")
setup_msvc_vars(OPTIONAL)
