class PCP_over_USB:
    def __init__(self, port, connect_on_init=True, logger=None): ...
    def connect(self, port=None): ...
    def disconnect(self): ...
    def close(self): ...
    def setCallback(self, address: int, callback: callable) -> None: ...
    def send_PCP(self, address: int, data: list): ...
    def enter_bootloader(self): ...
    @staticmethod
    def get_ports(): ...
    @staticmethod
    def get_port(): ...
    @property
    def is_connected(self): ...
