# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BinaryOp.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x42inaryOp.proto\x12\tmojo.spec\"\xd9\x01\n\rConstBinaryOp\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.mojo.spec.BinaryOpType\x12(\n\x03pos\x18\x02 \x01(\x0e\x32\x1b.mojo.spec.BinaryOpPosition\x12\x13\n\tint32_val\x18\x03 \x01(\x05H\x00\x12\x13\n\tint64_val\x18\x04 \x01(\x03H\x00\x12\x15\n\x0b\x66loat32_val\x18\x05 \x01(\x02H\x00\x12\x15\n\x0b\x66loat64_val\x18\x06 \x01(\x01H\x00\x12\x12\n\x08\x62ool_val\x18\x07 \x01(\x08H\x00\x42\x0b\n\tconst_val\"j\n\x08\x42inaryOp\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.mojo.spec.BinaryOpType\x12\x15\n\x0b\x66loat32_eps\x18\x02 \x01(\x02H\x00\x12\x15\n\x0b\x66loat64_eps\x18\x03 \x01(\x01H\x00\x42\t\n\x07\x65psilon*p\n\x0c\x42inaryOpType\x12\x1a\n\x16UNKNOWN_BINARY_OP_TYPE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x0c\n\x08SUBTRACT\x10\x02\x12\x0c\n\x08MULTIPLY\x10\x03\x12\n\n\x06\x44IVIDE\x10\x04\x12\x07\n\x03POW\x10\x05\x12\n\n\x06MODULO\x10\x06*G\n\x10\x42inaryOpPosition\x12\x1e\n\x1aUNKNOWN_BINARY_OP_POSITION\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BinaryOp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BINARYOPTYPE']._serialized_start=357
  _globals['_BINARYOPTYPE']._serialized_end=469
  _globals['_BINARYOPPOSITION']._serialized_start=471
  _globals['_BINARYOPPOSITION']._serialized_end=542
  _globals['_CONSTBINARYOP']._serialized_start=30
  _globals['_CONSTBINARYOP']._serialized_end=247
  _globals['_BINARYOP']._serialized_start=249
  _globals['_BINARYOP']._serialized_end=355
# @@protoc_insertion_point(module_scope)
