# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs2

# Types of operation state
class CurrentState(object):
    # User tasks and callables will executed, changes to the configuration might not be permitted, action with influence on the real-time behavior (like app installation) are not allowed
    OPERATING = 0
    # User tasks and callables will executed, changes to the configuration are permitted, action with influence on the real-time behavior (like app installation) are not allowed
    SETUP = 1
    # User tasks and callables are not executed, action with influence on the real-time behavior can be performed
    SERVICE = 2
    # Termination of task is pending
    EXIT = 3
