
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-09T10:39:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f79736604095a23352762a288f5bfd3a8ba27ce",
 "version": "5.7.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
