# automatically generated by the FlatBuffers compiler, do not modify

# namespace: API

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RemoveSource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRemoveSource(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoveSource()
        x.Init(buf, n + offset)
        return x

    # RemoveSource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoveSource
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RemoveSourceStart(builder): builder.StartObject(1)
def RemoveSourceAddSourceId(builder, sourceId): builder.PrependUint32Slot(0, sourceId, 0)
def RemoveSourceEnd(builder): return builder.EndObject()
