# automatically generated by the FlatBuffers compiler, do not modify

# namespace: API

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetNearestMode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSetNearestMode(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetNearestMode()
        x.Init(buf, n + offset)
        return x

    # SetNearestMode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetNearestMode
    def Active(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetNearestModeStart(builder): builder.StartObject(1)
def SetNearestModeAddActive(builder, active): builder.PrependBoolSlot(0, active, 0)
def SetNearestModeEnd(builder): return builder.EndObject()
