
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-12T16:27:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc64d0dd2d1c3e0845d13d30c4b8c1a605966c48",
 "version": "1.0b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
