# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

#This node delivers slave info data of a configured slave from the EtherCAT Master
class DcSlaveOnlineInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DcSlaveOnlineInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDcSlaveOnlineInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DcSlaveOnlineInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DcSlaveOnlineInfo
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.AddressedRequest import AddressedRequest
            obj = AddressedRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DcSlaveOnlineInfo
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.DcSlaveOnlineInfoResponse import DcSlaveOnlineInfoResponse
            obj = DcSlaveOnlineInfoResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DcSlaveOnlineInfoStart(builder): builder.StartObject(2)
def Start(builder):
    return DcSlaveOnlineInfoStart(builder)
def DcSlaveOnlineInfoAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def AddRequest(builder, request):
    return DcSlaveOnlineInfoAddRequest(builder, request)
def DcSlaveOnlineInfoAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def AddResponse(builder, response):
    return DcSlaveOnlineInfoAddResponse(builder, response)
def DcSlaveOnlineInfoEnd(builder): return builder.EndObject()
def End(builder):
    return DcSlaveOnlineInfoEnd(builder)
import comm.ethercat.master.fbs.AddressedRequest
import comm.ethercat.master.fbs.DcSlaveOnlineInfoResponse
try:
    from typing import Optional
except:
    pass

class DcSlaveOnlineInfoT(object):

    # DcSlaveOnlineInfoT
    def __init__(self):
        self.request = None  # type: Optional[comm.ethercat.master.fbs.AddressedRequest.AddressedRequestT]
        self.response = None  # type: Optional[comm.ethercat.master.fbs.DcSlaveOnlineInfoResponse.DcSlaveOnlineInfoResponseT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dcSlaveOnlineInfo = DcSlaveOnlineInfo()
        dcSlaveOnlineInfo.Init(buf, pos)
        return cls.InitFromObj(dcSlaveOnlineInfo)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dcSlaveOnlineInfo):
        x = DcSlaveOnlineInfoT()
        x._UnPack(dcSlaveOnlineInfo)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.request == other.request and \
            self.response == other.response

    # DcSlaveOnlineInfoT
    def _UnPack(self, dcSlaveOnlineInfo):
        if dcSlaveOnlineInfo is None:
            return
        if dcSlaveOnlineInfo.Request() is not None:
            self.request = comm.ethercat.master.fbs.AddressedRequest.AddressedRequestT.InitFromObj(dcSlaveOnlineInfo.Request())
        if dcSlaveOnlineInfo.Response() is not None:
            self.response = comm.ethercat.master.fbs.DcSlaveOnlineInfoResponse.DcSlaveOnlineInfoResponseT.InitFromObj(dcSlaveOnlineInfo.Response())

    # DcSlaveOnlineInfoT
    def Pack(self, builder):
        if self.request is not None:
            request = self.request.Pack(builder)
        if self.response is not None:
            response = self.response.Pack(builder)
        DcSlaveOnlineInfoStart(builder)
        if self.request is not None:
            DcSlaveOnlineInfoAddRequest(builder, request)
        if self.response is not None:
            DcSlaveOnlineInfoAddResponse(builder, response)
        dcSlaveOnlineInfo = DcSlaveOnlineInfoEnd(builder)
        return dcSlaveOnlineInfo
