# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

#Master sync unit id to name request.
class MsuIdToNameRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MsuIdToNameRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMsuIdToNameRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MsuIdToNameRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    #Master sync unit id.
    # MsuIdToNameRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def MsuIdToNameRequestStart(builder): builder.StartObject(1)
def Start(builder):
    return MsuIdToNameRequestStart(builder)
def MsuIdToNameRequestAddId(builder, id): builder.PrependUint16Slot(0, id, 0)
def AddId(builder, id):
    return MsuIdToNameRequestAddId(builder, id)
def MsuIdToNameRequestEnd(builder): return builder.EndObject()
def End(builder):
    return MsuIdToNameRequestEnd(builder)

class MsuIdToNameRequestT(object):

    # MsuIdToNameRequestT
    def __init__(self):
        self.id = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        msuIdToNameRequest = MsuIdToNameRequest()
        msuIdToNameRequest.Init(buf, pos)
        return cls.InitFromObj(msuIdToNameRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, msuIdToNameRequest):
        x = MsuIdToNameRequestT()
        x._UnPack(msuIdToNameRequest)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.id == other.id

    # MsuIdToNameRequestT
    def _UnPack(self, msuIdToNameRequest):
        if msuIdToNameRequest is None:
            return
        self.id = msuIdToNameRequest.Id()

    # MsuIdToNameRequestT
    def Pack(self, builder):
        MsuIdToNameRequestStart(builder)
        MsuIdToNameRequestAddId(builder, self.id)
        msuIdToNameRequest = MsuIdToNameRequestEnd(builder)
        return msuIdToNameRequest
