# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

#This node converts master sync unit name to id.
class MsuNameToId(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MsuNameToId()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMsuNameToId(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MsuNameToId
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MsuNameToId
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.MsuNameToIdRequest import MsuNameToIdRequest
            obj = MsuNameToIdRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MsuNameToId
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.ethercat.master.fbs.MsuNameToIdResponse import MsuNameToIdResponse
            obj = MsuNameToIdResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MsuNameToIdStart(builder): builder.StartObject(2)
def Start(builder):
    return MsuNameToIdStart(builder)
def MsuNameToIdAddRequest(builder, request): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)
def AddRequest(builder, request):
    return MsuNameToIdAddRequest(builder, request)
def MsuNameToIdAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def AddResponse(builder, response):
    return MsuNameToIdAddResponse(builder, response)
def MsuNameToIdEnd(builder): return builder.EndObject()
def End(builder):
    return MsuNameToIdEnd(builder)
import comm.ethercat.master.fbs.MsuNameToIdRequest
import comm.ethercat.master.fbs.MsuNameToIdResponse
try:
    from typing import Optional
except:
    pass

class MsuNameToIdT(object):

    # MsuNameToIdT
    def __init__(self):
        self.request = None  # type: Optional[comm.ethercat.master.fbs.MsuNameToIdRequest.MsuNameToIdRequestT]
        self.response = None  # type: Optional[comm.ethercat.master.fbs.MsuNameToIdResponse.MsuNameToIdResponseT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        msuNameToId = MsuNameToId()
        msuNameToId.Init(buf, pos)
        return cls.InitFromObj(msuNameToId)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, msuNameToId):
        x = MsuNameToIdT()
        x._UnPack(msuNameToId)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.request == other.request and \
            self.response == other.response

    # MsuNameToIdT
    def _UnPack(self, msuNameToId):
        if msuNameToId is None:
            return
        if msuNameToId.Request() is not None:
            self.request = comm.ethercat.master.fbs.MsuNameToIdRequest.MsuNameToIdRequestT.InitFromObj(msuNameToId.Request())
        if msuNameToId.Response() is not None:
            self.response = comm.ethercat.master.fbs.MsuNameToIdResponse.MsuNameToIdResponseT.InitFromObj(msuNameToId.Response())

    # MsuNameToIdT
    def Pack(self, builder):
        if self.request is not None:
            request = self.request.Pack(builder)
        if self.response is not None:
            response = self.response.Pack(builder)
        MsuNameToIdStart(builder)
        if self.request is not None:
            MsuNameToIdAddRequest(builder, request)
        if self.response is not None:
            MsuNameToIdAddResponse(builder, response)
        msuNameToId = MsuNameToIdEnd(builder)
        return msuNameToId
