from .multiple_linear_regression import MultipleLinearRegression
from .simple_linear_regression import SimpleLinearRegression
from .polynominal_regression import PolynomialRegression
from .logistic_regression import LogisticRegression
from .knn import KNN
from .naive_bayes import NaiveBayes
from .svm import SVM
from .k_means import K_Means
from .metrics import Metrics
from .preprocessing import Preprocessing
from .svm_fast import SVMFast
from .multiple_linear_regression_fast import MultipleLinearRegressionFast
from .logistic_regression_fast import LogisticRegressionFast
from .naive_bayes_fast import NaiveBayesFast
from .knn_fast import KNNFast
from .simple_linear_regression_fast import SimpleLinearRegressionFast
from .pca import PCA
from .polynominal_regression_fast import PolynomialRegressionFast
