# dictionary containing creole cardinal numbers from 10 to 99
ten_cardinal = {
    10: 'dis',
    11: 'onz',
    12: 'douz',
    13: 'trèz',
    14: 'katòz',
    15: 'kenz',
    16: 'sèz',
    17: 'disèt',
    18: 'dizuit',
    19: 'diznèf',

    20: 'ven',
    21: 'venteyen',
    22: 'vennde',
    23: 'venntwa',
    24: 'vennkat',
    25: 'vennsenk',
    26: 'vennsis',
    27: 'vennsèt',
    28: 'venntuit',
    29: 'ventnèf',

    30: 'trant',
    31: 'tranteyen',
    32: 'trannde',
    33: 'tranntwa',
    34: 'trannkat',
    35: 'tannsenk',
    36: 'trannsis',
    37: 'trannsèt',
    38: 'tranntuit',
    39: 'trantnèf',

    40: 'karant',
    41: 'karanteyen',
    42: 'karannde',
    43: 'karanntwa',
    44: 'karannkat',
    45: 'karannsenk',
    46: 'karannsis',
    47: 'karannsèt',
    48: 'karantuit',
    49: 'karantnèf',

    50: 'senkant',
    51: 'sekanteyen',
    52: 'senkannde',
    53: 'senkanntwa',
    54: 'senkannkat',
    55: 'sekannsenk',
    56: 'senkannsis',
    57: 'senkannsèt',
    58: 'sekantuit',
    59: 'senkantnèf',

    60: 'swasant',
    61: 'swasanteyen',
    62: 'swasannde',
    63: 'swasannwa',
    64: 'swasannkat',
    65: 'swasannsenk',
    66: 'swasannsis',
    67: 'swasannsèt',
    68: 'swasanntuit',
    69: 'swasantnèf',

    70: 'swasantdis',
    71: 'swasantonz',
    72: 'swasanndouz',
    73: 'swasanntrèz',
    74: 'swasannkatòz',
    75: 'swasannkenz',
    76: 'swasantsèz',
    77: 'swasanndisèt',
    78: 'swasanndizuit',
    79: 'swasanndisnèf',

    80: 'katreven',
    81: 'katrevenen',
    82: 'katrevende',
    83: 'katreventwa',
    84: 'katrevenkat',
    85: 'katrevensenk',
    86: 'katrevensis',
    87: 'katrevensèt',
    88: 'katrevenuit',
    89: 'katrevennèf',

    90: 'katrevendis',
    91: 'katevenonz',
    92: 'katrevendouz',
    93: 'katreventrèz',
    94: 'katrevenkatòz',
    95: 'katrevenkenz',
    96: 'katrevensèz',
    97: 'katrevendisèt',
    98: 'katrevendizuit',
    99: 'katrevendisnèf',

}


# dictionary containing the creole ordinal number
unit_ordinal = {
    1: 'premye',
    2: 'dezyèm',
    3: 'twazyèm',
    4: 'katriyèm',
    5: 'senkyèm',
    6: 'sizyèm',
    7: 'sètyèm',
    8: 'uityèm',
    9: 'nevyèm'
}

# dictionary containing creole ordinal numbers from 10 to 99
ten_ordinal = {
    10: 'dizyèm',
    11: 'onzyèm',
    12: 'douzyèm',
    13: 'trèzyèm',
    14: 'katòzyèm',
    15: 'kenzyèm',
    16: 'sèzyèm',
    17: 'disetyèm',
    18: 'dizuityèm',
    19: 'diznevyèm',

    20: 'ventyèm',
    21: 'venteyinyèm',
    22: 'venndezyèm',
    23: 'venntwazyèm',
    24: 'vennkatriyèm',
    25: 'vennsenkyèm',
    26: 'vennsizyèm',
    27: 'vennsetyèm',
    28: 'venntuityèm',
    29: 'ventnevyèm',

    30: 'trantyèm',
    31: 'tranteyinyèm',
    32: 'tranndezyèm',
    33: 'tranntwazyèm',
    34: 'trannkatriyèm',
    35: 'tannsenkyèm',
    36: 'trannsizyèm',
    37: 'trannsetyèm',
    38: 'tranntuityèm',
    39: 'trantnevyèm',

    40: 'karantyèm',
    41: 'karanteyinyèm',
    42: 'karanndezyèm',
    43: 'karanntwazyèm',
    44: 'karannkatriyèm',
    45: 'karannsenkyèm',
    46: 'karannsizyèm',
    47: 'karannsetyèm',
    48: 'karantuityèm',
    49: 'karantnevyèm',

    50: 'senkantyèm',
    51: 'sekanteyinyèm',
    52: 'senkanndezyèm',
    53: 'senkanntwazyèm',
    54: 'senkannkatriyèm',
    55: 'sekannsenkyèm',
    56: 'senkannsizyèm',
    57: 'senkannsetyèm',
    58: 'sekantuityèm',
    59: 'senkantnevyèm',

    60: 'swasantyèm',
    61: 'swasanteyinyèm',
    62: 'swasanndezyèm',
    63: 'swasannwazyèm',
    64: 'swasannkatriyèm',
    65: 'swasannsenkyèm',
    66: 'swasannsizyèm',
    67: 'swasannsetyèm',
    68: 'swasanntuityèm',
    69: 'swasantnevyèm',

    70: 'swasantdizyèm',
    71: 'swasantonzyèm',
    72: 'swasanndouzyèm',
    73: 'swasanntrèzyèm',
    74: 'swasannkatòzyèm',
    75: 'swasannkenzyèm',
    76: 'swasantsèzyèm',
    77: 'swasanndisètyèm',
    78: 'swasanndizuityèm',
    79: 'swasanndisnevyèm',

    80: 'katreventyèm',
    81: 'katreveninyèm',
    82: 'katrevendezyèm',
    83: 'katreventwazyèm',
    84: 'katrevenkatriyèm',
    85: 'katrevensenkyèm',
    86: 'katrevensizyèm',
    87: 'katrevensetyèm',
    88: 'katrevenuityèm',
    89: 'katrevennevyèm',

    90: 'katrevendizyèm',
    91: 'katevenonzyèm',
    92: 'katrevendouzyèm',
    93: 'katreventrèzyèm',
    94: 'katrevenkatòzyèm',
    95: 'katrevenkenzyèm',
    96: 'katrevensèzyèm',
    97: 'katrevendisètyèm',
    98: 'katrevendizuityèm',
    99: 'katrevendisnevyèm',
}
