__title__ = 'coplin-db2'
__version__ = '2.4'
__url__ = 'https://github.com/COPLIN-UFSM/db2'
__author__ = 'Henry Cagnini'
__author_email__ = 'henry.cagnini@ufsm.br'
__description__ = 'Um módulo de conveniência para manipulação de bancos de dados IBM DB2 em Python.'
__license__ = 'MIT'
__copyright__ = 'Henry Cagnini'
