# coding: utf-8

"""
    Discord HTTP API (Preview)

    Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

    The version of the OpenAPI document: 10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ThreadMetadataResponse(BaseModel):
    """
    ThreadMetadataResponse
    """ # noqa: E501
    archived: StrictBool
    archive_timestamp: Optional[datetime] = None
    auto_archive_duration: StrictInt
    locked: StrictBool
    create_timestamp: Optional[datetime] = None
    invitable: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["archived", "archive_timestamp", "auto_archive_duration", "locked", "create_timestamp", "invitable"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThreadMetadataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if archive_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.archive_timestamp is None and "archive_timestamp" in self.model_fields_set:
            _dict['archive_timestamp'] = None

        # set to None if create_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.create_timestamp is None and "create_timestamp" in self.model_fields_set:
            _dict['create_timestamp'] = None

        # set to None if invitable (nullable) is None
        # and model_fields_set contains the field
        if self.invitable is None and "invitable" in self.model_fields_set:
            _dict['invitable'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThreadMetadataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archived": obj.get("archived"),
            "archive_timestamp": obj.get("archive_timestamp"),
            "auto_archive_duration": obj.get("auto_archive_duration"),
            "locked": obj.get("locked"),
            "create_timestamp": obj.get("create_timestamp"),
            "invitable": obj.get("invitable")
        })
        return _obj


