# automatically generated by the FlatBuffers compiler, do not modify

# namespace: subtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DataSetReaderMessageDataType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataSetReaderMessageDataType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataSetReaderMessageDataType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataSetReaderMessageDataType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataSetReaderMessageDataType
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DataSetReaderMessageDataType
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def DataSetReaderMessageDataTypeStart(builder): builder.StartObject(2)
def Start(builder):
    return DataSetReaderMessageDataTypeStart(builder)
def DataSetReaderMessageDataTypeAddValueType(builder, valueType): builder.PrependUint8Slot(0, valueType, 0)
def AddValueType(builder, valueType):
    return DataSetReaderMessageDataTypeAddValueType(builder, valueType)
def DataSetReaderMessageDataTypeAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return DataSetReaderMessageDataTypeAddValue(builder, value)
def DataSetReaderMessageDataTypeEnd(builder): return builder.EndObject()
def End(builder):
    return DataSetReaderMessageDataTypeEnd(builder)
import comm.opcua.structure.JsonDataSetReaderMessageDataType
import comm.opcua.structure.UadpDataSetReaderMessageDataType
import comm.opcua.subtypesunion.DataSetReaderMessageDataType
try:
    from typing import Union
except:
    pass

class DataSetReaderMessageDataTypeT(object):

    # DataSetReaderMessageDataTypeT
    def __init__(self):
        self.valueType = 0  # type: int
        self.value = None  # type: Union[None, comm.opcua.structure.UadpDataSetReaderMessageDataType.UadpDataSetReaderMessageDataTypeT, comm.opcua.structure.JsonDataSetReaderMessageDataType.JsonDataSetReaderMessageDataTypeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dataSetReaderMessageDataType = DataSetReaderMessageDataType()
        dataSetReaderMessageDataType.Init(buf, pos)
        return cls.InitFromObj(dataSetReaderMessageDataType)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dataSetReaderMessageDataType):
        x = DataSetReaderMessageDataTypeT()
        x._UnPack(dataSetReaderMessageDataType)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.valueType == other.valueType and \
            self.value == other.value

    # DataSetReaderMessageDataTypeT
    def _UnPack(self, dataSetReaderMessageDataType):
        if dataSetReaderMessageDataType is None:
            return
        self.valueType = dataSetReaderMessageDataType.ValueType()
        self.value = comm.opcua.subtypesunion.DataSetReaderMessageDataType.DataSetReaderMessageDataTypeCreator(self.valueType, dataSetReaderMessageDataType.Value())

    # DataSetReaderMessageDataTypeT
    def Pack(self, builder):
        if self.value is not None:
            value = self.value.Pack(builder)
        DataSetReaderMessageDataTypeStart(builder)
        DataSetReaderMessageDataTypeAddValueType(builder, self.valueType)
        if self.value is not None:
            DataSetReaderMessageDataTypeAddValue(builder, value)
        dataSetReaderMessageDataType = DataSetReaderMessageDataTypeEnd(builder)
        return dataSetReaderMessageDataType
