#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2504-11-gfea644ae"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2504
#define NETGEN_VERSION_TWEAK 11
#define NETGEN_VERSION_HASH "gfea644ae"
#endif // NETGEN_VERSION_HPP_INCLUDED
