# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# configuration of all calculation steps of a single calculation pipeline
class AxsCfgCalcStepAll(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AxsCfgCalcStepAll()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAxsCfgCalcStepAll(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AxsCfgCalcStepAll
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # vector of all steps
    # AxsCfgCalcStepAll
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from motion.sync.fbtypes.AxsCfgCalcStep import AxsCfgCalcStep
            obj = AxsCfgCalcStep()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AxsCfgCalcStepAll
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AxsCfgCalcStepAll
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def AxsCfgCalcStepAllStart(builder): builder.StartObject(1)
def Start(builder):
    return AxsCfgCalcStepAllStart(builder)
def AxsCfgCalcStepAllAddSteps(builder, steps): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)
def AddSteps(builder, steps):
    return AxsCfgCalcStepAllAddSteps(builder, steps)
def AxsCfgCalcStepAllStartStepsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartStepsVector(builder, numElems):
    return AxsCfgCalcStepAllStartStepsVector(builder, numElems)
def AxsCfgCalcStepAllEnd(builder): return builder.EndObject()
def End(builder):
    return AxsCfgCalcStepAllEnd(builder)
import motion.sync.fbtypes.AxsCfgCalcStep
try:
    from typing import List
except:
    pass

class AxsCfgCalcStepAllT(object):

    # AxsCfgCalcStepAllT
    def __init__(self):
        self.steps = None  # type: List[motion.sync.fbtypes.AxsCfgCalcStep.AxsCfgCalcStepT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        axsCfgCalcStepAll = AxsCfgCalcStepAll()
        axsCfgCalcStepAll.Init(buf, pos)
        return cls.InitFromObj(axsCfgCalcStepAll)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, axsCfgCalcStepAll):
        x = AxsCfgCalcStepAllT()
        x._UnPack(axsCfgCalcStepAll)
        return x

    def __eq__(self, other):
        return type(self) == type(other) and \
            self.steps == other.steps

    # AxsCfgCalcStepAllT
    def _UnPack(self, axsCfgCalcStepAll):
        if axsCfgCalcStepAll is None:
            return
        if not axsCfgCalcStepAll.StepsIsNone():
            self.steps = []
            for i in range(axsCfgCalcStepAll.StepsLength()):
                if axsCfgCalcStepAll.Steps(i) is None:
                    self.steps.append(None)
                else:
                    axsCfgCalcStep_ = motion.sync.fbtypes.AxsCfgCalcStep.AxsCfgCalcStepT.InitFromObj(axsCfgCalcStepAll.Steps(i))
                    self.steps.append(axsCfgCalcStep_)

    # AxsCfgCalcStepAllT
    def Pack(self, builder):
        if self.steps is not None:
            stepslist = []
            for i in range(len(self.steps)):
                stepslist.append(self.steps[i].Pack(builder))
            AxsCfgCalcStepAllStartStepsVector(builder, len(self.steps))
            for i in reversed(range(len(self.steps))):
                builder.PrependUOffsetTRelative(stepslist[i])
            steps = builder.EndVector()
        AxsCfgCalcStepAllStart(builder)
        if self.steps is not None:
            AxsCfgCalcStepAllAddSteps(builder, steps)
        axsCfgCalcStepAll = AxsCfgCalcStepAllEnd(builder)
        return axsCfgCalcStepAll
