from __future__ import annotations

FILTER_PHRASES: list[str] = [
    "-",
    "/",
    "\\",
    "|",
    "Already up to date",
    "Attempting uninstall",
    "Building wheel for ",
    "Building wheels for collected packages: ",
    "Cloning ",
    "Collecting",
    "Created wheel for ",
    "done",
    "dulwich",
    "Everything up-to-date",
    "Fetching submodule",
    "Found existing installation: ",
    "Getting requirements to build wheel",
    "Installing build dependencies",
    "Installing collected packages: ",
    "keyring",
    "Preparing metadata (pyproject.toml)",
    "Requirement already satisfied:",
    "Resolved ",
    "Running command git clone --filter=blob:none --quiet ",
    "Stored in directory: ",
    "Successfully built ",
    "Successfully installed ",
    "Successfully uninstalled ",
    "Uninstalling ",
    "Using cached",
]
