cmake_minimum_required(VERSION 3.27)

include_guard(GLOBAL)

message(CHECK_START "Checking spdlog provider")

if(AXSERVE_SPDLOG_PROVIDER STREQUAL "module")
    set(SPDLOG_EXTERNAL_NAME "spdlog")
    set(SPDLOG_PREFIX_NAME "spdlog")
    set(SPDLOG_THIRD_PARTY_NAME "spdlog")

    set(SPDLOG_GIT_REPOSITORY "https://github.com/gabime/spdlog.git")
    set(SPDLOG_GIT_TAG "v1.15.3")

    set(SPDLOG_CMAKE_CACHE_ARGS
        "-DCMAKE_SYSTEM_NAME:STRING=${CMAKE_SYSTEM_NAME}"
        "-DCMAKE_SYSTEM_VERSION:STRING=${CMAKE_SYSTEM_VERSION}"
        "-DCMAKE_SYSTEM_PROCESSOR:STRING=${CMAKE_SYSTEM_PROCESSOR}"
        "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DCMAKE_CXX_STANDARD:STRING=${CMAKE_CXX_STANDARD}"
        "-DCMAKE_CXX_STANDARD_REQUIRED:BOOL=${CMAKE_CXX_STANDARD_REQUIRED}"
        "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
    )

    include("${CMAKE_CURRENT_LIST_DIR}/../util/external-project.cmake")

    ExternalProject_AddForThisProject("${SPDLOG_EXTERNAL_NAME}"
        PREFIX_NAME "${SPDLOG_PREFIX_NAME}"
        THIRD_PARTY_NAME "${SPDLOG_THIRD_PARTY_NAME}"
        GIT_REPOSITORY "${SPDLOG_GIT_REPOSITORY}"
        GIT_TAG "${SPDLOG_GIT_TAG}"
        CMAKE_CACHE_ARGS ${SPDLOG_CMAKE_CACHE_ARGS}
        DEPENDS ${SPDLOG_DEPENDS}
        START_UNPARSED_ARGUMENTS
        LOG_CONFIGURE TRUE
        LOG_BUILD TRUE
        LOG_OUTPUT_ON_FAILURE TRUE
    )

    message(CHECK_PASS "${AXSERVE_SPDLOG_PROVIDER}")
elseif(AXSERVE_SPDLOG_PROVIDER STREQUAL "package")
    find_package(spdlog CONFIG REQUIRED)
    message(CHECK_PASS "${AXSERVE_SPDLOG_PROVIDER}")
else()
    message(CHECK_FAIL "${AXSERVE_SPDLOG_PROVIDER}")
endif()
