from typing import Any, Optional, Tuple, TypeVar, Generic

T = TypeVar('T')

class PyRouter(Generic[T]):
    def __init__(self) -> None: ...
    def insert(self, path: str, value: T) -> None: ...
    def at(self, path: str) -> Optional[Tuple[T, dict[str, Any]]]: ...
    def remove(self, path: str) -> bool: ...
    def clear(self) -> None: ...
    def __repr__(self) -> str: ...
